Notification
Conflux-Chain/react-ui pull request #121
Opened 2020-12-07 11:21 UTC by chain-txz

## Checklist

- [ ] Fix linting errors
- [ ] Tests have been added / updated (or snapshots)

## Change information

2020-12-09 08:13 UTC, angelia-yuqi-personal requested changes

2020-12-09 08:13 UTC, angelia-yuqi-personal commented on pages/en-us/components/notification.mdx
> +| **placement** | position of the popover relative to the window   | `string`               | -                        | `right-start` |
need to define the type NotificationPlacement ,it's not string

2020-12-09 11:52 UTC, angelia-yuqi-personal approved these changes

2020-12-10 06:08 UTC, zctocm approved these changes

2020-12-10 06:09 UTC, merged